In [1]:
import numpy as np
import pandas as pd

In [5]:
data=pd.read_csv(r"C:\Users\nidhi\Downloads\Telegram Desktop\bank.csv")

In [6]:
data.head()

age         job  marital  education default  balance housing loan  contact  \
0   59      admin.  married  secondary      no     2343     yes   no  unknown   
1   56      admin.  married  secondary      no       45      no   no  unknown   
2   41  technician  married  secondary      no     1270     yes   no  unknown   
3   55    services  married  secondary      no     2476     yes   no  unknown   
4   54      admin.  married   tertiary      no      184      no   no  unknown   

   day month  duration  campaign  pdays  previous poutcome deposit  
0    5   may      1042         1     -1         0  unknown     yes  
1    5   may      1467         1     -1         0  unknown     yes  
2    5   may      1389         1     -1         0  unknown     yes  
3    5   may       579         1     -1         0  unknown     yes  
4    5   may       673         2     -1         0  unknown     yes

In [7]:
data.shape

(11162, 17)

In [8]:
data.describe()

age       balance           day      duration      campaign  \
count  11162.000000  11162.000000  11162.000000  11162.000000  11162.000000   
mean      41.231948   1528.538524     15.658036    371.993818      2.508421   
std       11.913369   3225.413326      8.420740    347.128386      2.722077   
min       18.000000  -6847.000000      1.000000      2.000000      1.000000   
25%       32.000000    122.000000      8.000000    138.000000      1.000000   
50%       39.000000    550.000000     15.000000    255.000000      2.000000   
75%       49.000000   1708.000000     22.000000    496.000000      3.000000   
max       95.000000  81204.000000     31.000000   3881.000000     63.000000   

              pdays      previous  
count  11162.000000  11162.000000  
mean      51.330407      0.832557  
std      108.758282      2.292007  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       20.750000      1.000000  
max      854.000000     58.000000

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   age        11162 non-null  int64 
 1   job        11162 non-null  object
 2   marital    11162 non-null  object
 3   education  11162 non-null  object
 4   default    11162 non-null  object
 5   balance    11162 non-null  int64 
 6   housing    11162 non-null  object
 7   loan       11162 non-null  object
 8   contact    11162 non-null  object
 9   day        11162 non-null  int64 
 10  month      11162 non-null  object
 11  duration   11162 non-null  int64 
 12  campaign   11162 non-null  int64 
 13  pdays      11162 non-null  int64 
 14  previous   11162 non-null  int64 
 15  poutcome   11162 non-null  object
 16  deposit    11162 non-null  object
dtypes: int64(7), object(10)
memory usage: 1.4+ MB


In [10]:
data.isnull().any()

age          False
job          False
marital      False
education    False
default      False
balance      False
housing      False
loan         False
contact      False
day          False
month        False
duration     False
campaign     False
pdays        False
previous     False
poutcome     False
deposit      False
dtype: bool

In [11]:
data.drop(['duration'],axis=1,inplace=True)

In [12]:
#label encoding

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data['job']=le.fit_transform(data['job'])
data['marital']=le.fit_transform(data['marital'])
data['education']=le.fit_transform(data['education'])
data['default']=le.fit_transform(data['default'])
data['housing']=le.fit_transform(data['housing'])
data['loan']=le.fit_transform(data['loan'])
data['contact']=le.fit_transform(data['contact'])
data['month']=le.fit_transform(data['month'])
data['poutcome']=le.fit_transform(data['poutcome'])
data['deposit']=le.fit_transform(data['deposit'])


In [13]:
data

age  job  marital  education  default  balance  housing  loan  contact  \
0       59    0        1          1        0     2343        1     0        2   
1       56    0        1          1        0       45        0     0        2   
2       41    9        1          1        0     1270        1     0        2   
3       55    7        1          1        0     2476        1     0        2   
4       54    0        1          2        0      184        0     0        2   
...    ...  ...      ...        ...      ...      ...      ...   ...      ...   
11157   33    1        2          0        0        1        1     0        0   
11158   39    7        1          1        0      733        0     0        2   
11159   32    9        2          1        0       29        0     0        0   
11160   43    9        1          1        0        0        0     1        0   
11161   34    9        1          1        0        0        0     0        0   

       day  month  campaign  pdays  previous  poutcome  deposit  
0        5      8         1     -1         0         3        1  
1        5      8         1     -1         0         3        1  
2        5      8         1     -1         0         3        1  
3        5      8         1     -1         0         3        1  
4        5      8         2     -1         0         3        1  
...    ...    ...       ...    ...       ...       ...      ...  
11157   20      0         1     -1         0         3        0  
11158   16      6         4     -1         0         3        0  
11159   19      1         2     -1         0         3        0  
11160    8      8         2    172         5         0        0  
11161    9      5         1     -1         0         3        0  

[11162 rows x 16 columns]

In [14]:
x=data.iloc[:,0:15].values
y=data.iloc[:,15:16].values

In [15]:
x.shape

(11162, 15)

In [16]:
y.shape

(11162, 1)

In [17]:
from sklearn.preprocessing import OneHotEncoder
one=OneHotEncoder()
s= one.fit_transform(x[:,1:2]).toarray()
t= one.fit_transform(x[:,2:3]).toarray()
u= one.fit_transform(x[:,3:4]).toarray()
v= one.fit_transform(x[:,8:9]).toarray()
w= one.fit_transform(x[:,10:11]).toarray()

In [18]:
s

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [19]:
s.shape

(11162, 12)

In [20]:
x=np.concatenate((s,t,u,v,w,x),axis=1)

In [21]:
x.shape

(11162, 49)

In [22]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2, random_state=0)

In [23]:
print(x_train.shape)#training input
print(x_test.shape)#testing input
print(y_train.shape)#training output
print(y_test.shape)#testing output

(8929, 49)
(2233, 49)
(8929, 1)
(2233, 1)


In [24]:
x_train

array([[ 0.,  0.,  0., ..., -1.,  0.,  3.],
       [ 0.,  0.,  0., ..., -1.,  0.,  3.],
       [ 0.,  1.,  0., ..., -1.,  0.,  3.],
       ...,
       [ 0.,  0.,  0., ..., -1.,  0.,  3.],
       [ 1.,  0.,  0., ..., -1.,  0.,  3.],
       [ 0.,  0.,  0., ..., -1.,  0.,  3.]])

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [26]:
x_train

array([[-0.37172192, -0.45760242, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265],
       [-0.37172192,  2.18530314, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265],
       ...,
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265],
       [ 2.69018306, -0.45760242, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265],
       [-0.37172192, -0.45760242, -0.17658264, ..., -0.48428507,
        -0.35888264,  0.52269265]])